### ISSUE TITLE
Fix deploy step in CI failing

### ISSUE THREAD

**Issue by e00E** [gnosis/dex-services#958]
The new rust version introduced more warnings or lints that make master
fail in the ethcontract generated code. https://travis-ci.com/github/gnosis/dex-services/jobs/343998701

https://github.com/gnosis/dex-services/pull/957

**Comment by e00E** [comment]
Description above can't be fully correct because it doesn't happen locally.

**Comment by e00E** [comment]
It is weird that CI is succeeding for PRs but not for master. It must be related to a difference in the jobs we run. I noticed that we have 
```
      cache:
        directories:
          - $HOME/.cache/yarn
          - $HOME/.cargo/bin
      before_cache:
        - rm -rf "$TRAVIS_HOME/.cargo/registry/src"
      env: CARGO_INCREMENTAL=0
```
only for PRs but not for deploy.
